name: check links

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

permissions: read-all

jobs:
  check-links:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4.1.6

      - name: run lychee link checker
        id: lychee
        uses: lycheeverse/lychee-action@2b973e86fc7b1f6b36a93795fe2c9c6ae1118621 # v1.10.0
        with:
          fail: true
          args: "--config=.lychee.toml ."
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
