name: check links

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

permissions: read-all

jobs:
  check-links:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1

      - name: run lychee link checker
        id: lychee
        uses: lycheeverse/lychee-action@c053181aa0c3d17606addfe97a9075a32723548a # v1.9.3
        with:
          fail: true
          args: "--config=.lychee.toml ."
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
