name: release-please

on:
  push:
    branches:
      - master

permissions:
  contents: read

jobs:
  release-please:
    runs-on: ubuntu-24.04
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: googleapis/release-please-action@16a9c90856f42705d54a6fda1823352bdc62cf38 # v4.4.0
        with:
          token: ${{ secrets.MIRACUM_BOT_SEMANTIC_RELEASE_TOKEN }}
